### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Allan-Nava** [obrunsmann/flutter_nakama#1]

**Comment by obrunsmann** [comment]
@Allan-Nava do you have specific questions? Or some things you not understand? Then I have a better idea as to what I can improve.

**Comment by Allan-Nava** [comment]
This is a nice to have like github page

**Comment by obrunsmann** [comment]
Hehe yeah, added a few minutes ago. You get it all @Allan-Nava  :))

I'm still working on it and adding the docs. The challenge is to not create and maintain a lot of duplications between the official documentation (which I think is very good) but still describe the Flutter SDK sufficiently.

I'm maintaining the docs now and if something is unclear, please create a new issue, which point should be improved.

**Comment by Allan-Nava** [comment]
No problem, If you need some help! I'm here
