### ISSUE TITLE
he current Dart SDK version is 2.9.2. |  Because nakama requires SDK version >=2.12.0 <3.0.0, version solving failed.

### ISSUE THREAD

**Issue by Allan-Nava** [obrunsmann/flutter_nakama#10]
I try to do `flutter packages get`

<img width="713" alt="Screenshot 2021-06-04 at 08 32 06" src="https://user-images.githubusercontent.com/22498435/120756373-74d17f00-c50f-11eb-95ed-3baadf110902.png">

**Comment by obrunsmann** [comment]
@Allan-Nava  Can you please share your full pubspec and the output of `flutter doctor`?

**Comment by Allan-Nava** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on macOS 11.2.2 20D80, locale en-IT)
⣾
 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.56.2)
[!] Connected device
    ! No devices available

**Comment by obrunsmann** [comment]
Seems you need to run `flutter upgrade` to get the latest stable version. Flutter 2.x is already stable and you're using 1.20.4 which is from Nov/2020.

This package only supports Flutter ≥2.x

**Comment by Allan-Nava** [comment]
> Seems you need to run `flutter upgrade` to get the latest stable version. Flutter 2.x is already stable and you're using 1.20.4 which is from Nov/2020.
> 
> This package only supports Flutter ≥2.x

Ok, thanks . Asap I try
