### ISSUE TITLE
The rpc method in the websocket client returns null

### ISSUE THREAD

**Issue by lchenneberg** [obrunsmann/flutter_nakama#17]
Hello, I'm facing some issues with rpc.

I try to call the rpc async method from the websocket client the Future returns null on every call;
In the server logs I can see that the method has been called.

Can you get a look and tell me what I am doing wrong?  

<img width="934" alt="Screen Shot 2021-07-17 at 1 06 45 AM" src="https://user-images.githubusercontent.com/1746548/126026423-98774be1-36d0-475c-8e7a-6aa093a3b172.png">
<img width="1185" alt="Screen Shot 2021-07-17 at 1 06 14 AM" src="https://user-images.githubusercontent.com/1746548/126026424-077513cd-31f4-428d-810c-61af0469871c.png">
<img width="475" alt="Screen Shot 2021-07-17 at 1 06 04 AM" src="https://user-images.githubusercontent.com/1746548/126026425-2cb5da20-4905-4b3a-8163-48cfdf53d265.png">
<img width="545" alt="Screen Shot 2021-07-17 at 1 05 34 AM" src="https://user-images.githubusercontent.com/1746548/126026426-f2c1268d-2be5-4067-a78a-2283e38850e2.png">

**Comment by Allan-Nava** [comment]
Also here: https://github.com/Allan-Nava/nakama-flutter/issues/4#issuecomment-882065806

**Comment by obrunsmann** [comment]
This package has not yet implemented gRPC function invocations. Next time please post all your code samples and logs as code snippets instead of screenshots and provide a minimal reproduce code and your pubspec.yaml.

**Comment by Zhairgling** [comment]
> This package has not yet implemented gRPC function invocations. Next time please post all your code samples and logs as code snippets instead of screenshots and provide a minimal reproduce code and your pubspec.yaml.

Is there any progress on this feature ?
