### ISSUE TITLE
Facebook friends import feature support in authenticate with facebook method

### ISSUE THREAD

**Issue by ZaheerFaisal** [obrunsmann/flutter_nakama#18]
It will be great to have this feature and it will be easy to import facebook friends into nakama friend's graph.

As described [here](https://heroiclabs.com/docs/nakama/concepts/authentication/#facebook):

"You can optionally import Facebook friends into Nakama's friend graph when authenticating. To do this, set import to true."

**Comment by obrunsmann** [comment]
Added the draft for import, Docs TBD
