### ISSUE TITLE
Authentication suddenly stops working

### ISSUE THREAD

**Issue by AxiatCode** [obrunsmann/flutter_nakama#19]
Authentication with Nakama server using SDK is not working and throwing this error in response:

flutter: gRPC Error (code: 2, codeName: UNKNOWN, message: HTTP/2 error: Connection error: Connection is being forcefully terminated. (errorCode: 10), details: null, rawResponse: null)

```
Future<bool> authenticateWithCustomAsync(
    BuildContext context, LoginDetails loginDetails) async {
  bool result = false;
  try {
    await getNakamaClient()
        .authenticateCustom(
            id: loginDetails.socialUserID!,
            username: loginDetails.socialUserName!.replaceAll(" ", ""))
        .then((session) {
      nakamaSession = session;
      result = true;
    });
  } catch (e) {
    hideLoading(context);
    print(e.hashCode);
    print(e.toString());
    result = false;
  }

```

**Comment by obrunsmann** [comment]
Can you please post your **Nakama version** and the stack you've used? Local via docker? Or Nakama's cloud? Then I can try to reproduce that.

I found this: https://stackoverflow.com/questions/66784095/unhandled-exception-grpc-error-in-flutter
Do you operate your Nakama server behind SSL/TLS? Please check to pass the correct `ssl: true|false` in the init of Nakama client like described here: https://flutter-nakama.gitbook.io/flutter-nakama/installation-and-setup#initialize-base-client

**Comment by AxiatCode** [comment]
Server version: 3.2.1+6790d453

We are using Nakama server hosted on windows machine and installed via docker.

We are not operating Nakama server over SSL or TLS.

After enabling SSL in initialization, getting this exception attached.

<img width="1275" alt="Screenshot 2021-09-01 at 10 23 07 PM" src="https://user-images.githubusercontent.com/79599201/131717672-f3d2353c-fea0-4fb3-98aa-5a9e8073e713.png">

**Comment by obrunsmann** [comment]
Okay thanks for Details. ssl: false is fully correct if you don't use TLS/SSL in your case.
Do you have the chance to post your runnable docker setup? Using docker compose? Would like trying to reproduce somehow...

**Comment by obrunsmann** [comment]
Maybe one more thing that just comes to mind:

Have you used the correct way to initialize the SDK which is described here https://flutter-nakama.gitbook.io/flutter-nakama/examples/minimal-example#initialize-sdk ?

The error could also occur if you mess the Web/Mobile includes which is automatically handled by the SDK if using correct methods.

**Comment by AxiatCode** [comment]
We have contacted our network engineer and after resolving the iptables issue, this is now fixed.

Thanks for the co-operation.

**Comment by obrunsmann** [comment]
Perfekt. Thanks for feedback.
