### ISSUE TITLE
Implement all auth methods

### ISSUE THREAD

**Issue by obrunsmann** [obrunsmann/flutter_nakama#3]
Several authentication providers like device token, apple, google, game center, etc. still missing.

**Comment by Allan-Nava** [comment]
And the custom authentication?

**Comment by obrunsmann** [comment]
Yess right, it's not a complete checklist above :)

**Comment by Allan-Nava** [comment]
Ok need some help?

**Comment by obrunsmann** [comment]
I will probably get to work on the missing Auth methods today.

If you like, feel free to add issues for methods you might want to use so priorities are clear :)

**Comment by obrunsmann** [comment]
Completed in the latest release.

**Comment by Allan-Nava** [comment]
Wow thanks!
