### ISSUE TITLE
Organize generated gRPC client

### ISSUE THREAD

**Issue by obrunsmann** [obrunsmann/flutter_nakama#4]
- [x] Publish model files from the library → No imports of the .pb.dart files should be necessary from outside the package
- [x] Remove unused generated files (some unit test files have been generated as well from google/protobuf package)

**Comment by Allan-Nava** [comment]
How can you handle the grpc stuff ?

**Comment by obrunsmann** [comment]
What do you mean?

**Comment by Allan-Nava** [comment]
> What do you mean?

Like this for nakama swift https://github.com/Allan-Nava/nakama-swift/tree/master/proto

**Comment by Allan-Nava** [comment]
> Hmm unfortunately I haven't quite figured out what you mean yet. This issue is about removing the files that are currently generated but not needed.
> 
> Is just clean up - not very critical :)

Ah ok, because in swift we generated automatically the swift files from proto

**Comment by obrunsmann** [comment]
Yeah right, doing same here (https://github.com/obrunsmann/flutter_nakama/blob/main/lib/api/generate.sh). But the problem I would like to solve is to organize the mass of generated API Docs for all the compiled pb stuff like here: https://pub.dev/documentation/nakama/latest

So the first thing might be to disable generation of unused pb files and the second thing might be to check if the files could get some namespaceing so that this flutter library not expose so many libraries

**Comment by Allan-Nava** [comment]
> Yeah right, doing same here (https://github.com/obrunsmann/flutter_nakama/blob/main/lib/api/generate.sh). But the problem I would like to solve is to organize the mass of generated API Docs for all the compiled pb stuff like here: https://pub.dev/documentation/nakama/latest
> 
> So the first thing might be to disable generation of unused pb files and the second thing might be to check if the files could get some namespaceing so that this flutter library not expose so many classes

Ok as you wish
