### ISSUE TITLE
start authoritative match?

### ISSUE THREAD

**Issue by tpham3783** [obrunsmann/flutter_nakama#44]
Hi,

I can only start a relayed match, is it possible to start an authoritative match?  thanks

**Comment by StochitaCatalin** [comment]
For authoritative match you need to implement your own logic in nakama. Something like this:
https://github.com/heroiclabs/nakama/blob/master/sample_go_module/sample.go

I have started using nakama 2 days ago but this should be it. I have tested the above example and is working, the match is created with authoritative flag(just be sure to delete tick>10 nil at line 146 so the server dont stop). To start a match you need to call the rpc method from flutter(rpc_create_match) and probably you need to create some logic in this method to create or return an existing match

**Comment by obrunsmann** [comment]
Here you can find the respective docs for it: https://heroiclabs.com/docs/nakama/concepts/multiplayer/authoritative/ :)
