### ISSUE TITLE
Storage Engine API

### ISSUE THREAD

**Issue by obrunsmann** [obrunsmann/flutter_nakama#6]
- [x] Read Objects
- [x] Write Objects
- [x] List Objects
- [x] Remove Objects

**Comment by AxiatCode** [comment]
Desperately waiting for it.

**Comment by kechkibet** [comment]
> Desperately waiting for it.

Seconded

**Comment by duck-dev-go** [comment]
+1

**Comment by aminalaee** [comment]
@obrunsmann I can help with this if already not done, I think only "write" method is done. Isn't it the case?
